package vista;
import controlador.DaoObjeto;
import enumeradores.EnumColor;
import enumeradores.EnumEscuela;
import enumeradores.EnumSemestre;
import enumeradores.EnumTipo;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Encontrado;
import modelo.Objeto;
import modelo.Sala;
import modelo.Recibido;

public class JFrmAgregarObjeto extends javax.swing.JFrame {

    /**
     * Creates new form JFrmAgregarObjeto
     */
    public JFrmAgregarObjeto() {
        initComponents();
        setLocationRelativeTo(null);
        Listar();
        cboColor.setModel(new DefaultComboBoxModel(EnumColor.values()));
        cboTipo.setModel(new DefaultComboBoxModel(EnumTipo.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jtblLista = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spnId_objeto = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtdesc_objeto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboColor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        spnId_sala = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        txtEncontradoRut = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRecibidoRut = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jtblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtblLista);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Objeto"));

        jLabel1.setText("Id Objeto");

        spnId_objeto.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));

        jLabel2.setText("Descripción Objeto:");

        jButton1.setText("Grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo:");

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Color:");

        cboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Fecha Encontrado:");

        jLabel6.setText("Id Sala:");

        spnId_sala.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel7.setText("Rut Encontrado por:");

        jLabel8.setText("Rut Recibido por:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spnId_objeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtdesc_objeto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spnId_sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jdcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEncontradoRut)
                            .addComponent(txtRecibidoRut, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnId_objeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdesc_objeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spnId_sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEncontradoRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRecibidoRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int id_objeto = Integer.parseInt(spnId_objeto.getValue().toString());
        String descripcion_objeto =txtdesc_objeto.getText();
        String tipo = cboTipo.getSelectedItem().toString();
        EnumTipo enum_tipo = null;
        if (tipo.equalsIgnoreCase("Teconlogia")) {
            enum_tipo = EnumTipo.Teconlogia;}
        if (tipo.equalsIgnoreCase("Cuadernos_Libros")){
            enum_tipo = EnumTipo.Cuadernos_Libros;}
        if (tipo.equalsIgnoreCase("Mochilas_Bolsos")){
            enum_tipo = EnumTipo.Mochilas_Bolsos;}
        if (tipo.equals("Accesorios")){
            enum_tipo = EnumTipo.Accesorios;}
        if (tipo.equalsIgnoreCase("Ropa")){
            enum_tipo = EnumTipo.Ropa;}
        if (tipo.equalsIgnoreCase("Otros")){
            enum_tipo = EnumTipo.Otros;}
        String color = cboColor.getSelectedItem().toString();
        EnumColor enum_color = null;
        if (color.equals("Negro")) {
            enum_color = EnumColor.Negro;}
        if (color.equals("Blanco")) {
            enum_color = EnumColor.Blanco;}
        if (color.equals("Rojo")) {
            enum_color = EnumColor.Rojo;}
        if (color.equals("Azul")) {
            enum_color = EnumColor.Azul;}
        if (color.equals("Amarillo")) {
            enum_color = EnumColor.Amarillo;}
        if (color.equals("Naranja")) {
            enum_color = EnumColor.Naranja;}
        if (color.equals("Rosado")) {
            enum_color = EnumColor.Rosado;}
        if (color.equals("Morado")) {
            enum_color = EnumColor.Morado;}
        if(color.equals("Otros")) {
            enum_color = EnumColor.Otros;}
        java.sql.Date fecha = new java.sql.Date(jdcFecha.getDate().getTime());
        Date fecha_encontrado = fecha;
        int id_sala = Integer.parseInt(spnId_sala.getValue().toString());
        Sala sal = new Sala(id_sala, descripcion_objeto);
        String rut_encontrado = txtEncontradoRut.getText();
        Encontrado enc = new Encontrado(rut_encontrado, rut_encontrado, rut_encontrado, EnumEscuela.Salud, EnumSemestre.S1);
        String rut_recibido = txtRecibidoRut.getText();
        Recibido rec = new Recibido(rut_recibido, rut_recibido, rut_recibido, EnumEscuela.Salud, EnumSemestre.S1);
        
        try {
            Objeto obj = new Objeto(id_objeto, descripcion_objeto, enum_tipo, enum_color, fecha_encontrado, sal, enc, rec);
            DaoObjeto dao = new DaoObjeto();
            boolean resp = dao.Grabar(obj);
            if (resp == true) {
                JOptionPane.showMessageDialog(null, "Grabo");
                limpiar();
                Listar();
            } else {
                JOptionPane.showMessageDialog(null, "No Grabo");
                limpiar();
                Listar();
            }
            
        } catch (Exception e) {
            System.out.println("Error Grabar objeto:"+e.getMessage());
        }
            

        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int pos_fila = jtblLista.getSelectedRow();
        int id_objeto = Integer.parseInt(jtblLista.getValueAt(pos_fila, 0).toString());
        try {
            DaoObjeto dao = new DaoObjeto();
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea eliminar objeto? "+id_objeto,
                            "Eliminar Objeto", JOptionPane.YES_NO_OPTION);
                if (respuesta == 0) {
                boolean resp = dao.Eliminar(id_objeto);
                if (resp) {
                    JOptionPane.showMessageDialog(null, "Eliminado");
                    limpiar();
                    Listar();
                } else {
                    JOptionPane.showMessageDialog(null, "No pudo eliminar");
                }
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error eliminar");
        }
 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int id_objeto= Integer.parseInt(spnId_objeto.getValue().toString());
        String descripcion_objeto =txtdesc_objeto.getText();
        String tipo = cboTipo.getSelectedItem().toString();
        EnumTipo enum_tipo = null;
        if (tipo.equalsIgnoreCase("Teconlogia")) {
            enum_tipo = EnumTipo.Teconlogia;}
        if (tipo.equalsIgnoreCase("Cuadernos_Libros")){
            enum_tipo = EnumTipo.Cuadernos_Libros;}
        if (tipo.equalsIgnoreCase("Mochilas_Bolsos")){
            enum_tipo = EnumTipo.Mochilas_Bolsos;}
        if (tipo.equalsIgnoreCase("Accesorios")){
            enum_tipo = EnumTipo.Accesorios;}
        if (tipo.equalsIgnoreCase("Ropa")){
            enum_tipo = EnumTipo.Ropa;}
        if (tipo.equalsIgnoreCase("Otros")){
            enum_tipo = EnumTipo.Otros;}
        String color = cboColor.getSelectedItem().toString();
        EnumColor enum_color = null;
        if (color.equals("Negro")) {
            enum_color = EnumColor.Negro;}
        if (color.equals("Blanco")) {
            enum_color = EnumColor.Blanco;}
        if (color.equals("Rojo")) {
            enum_color = EnumColor.Rojo;}
        if (color.equals("Azul")) {
            enum_color = EnumColor.Azul;}
        if (color.equals("Amarillo")) {
            enum_color = EnumColor.Amarillo;}
        if (color.equals("Naranja")) {
            enum_color = EnumColor.Naranja;}
        if (color.equals("Rosado")) {
            enum_color = EnumColor.Rosado;}
        if (color.equals("Morado")) {
            enum_color = EnumColor.Morado;}
        if(color.equals("Otros")) {
            enum_color = EnumColor.Otros;}
        java.sql.Date fecha = new java.sql.Date(jdcFecha.getDate().getTime());
        Date fecha_encontrado = fecha;
        int id_sala = Integer.parseInt(spnId_sala.getValue().toString());
        Sala sal = new Sala(id_sala, descripcion_objeto);
        String rut_encontrado = txtEncontradoRut.getText();
        Encontrado enc = new Encontrado(rut_encontrado, rut_encontrado, rut_encontrado, EnumEscuela.Salud, EnumSemestre.S1);
        String rut_recibido = txtRecibidoRut.getText();
        Recibido rec = new Recibido(rut_recibido, rut_recibido, rut_recibido, EnumEscuela.Salud, EnumSemestre.S1);
        
        
        try {
            Objeto obj = new Objeto(id_objeto, descripcion_objeto, enum_tipo, enum_color, fecha_encontrado, sal, enc, rec);
            int res= JOptionPane.showConfirmDialog(null, "Modificar","Modificar registro",
                    JOptionPane.YES_NO_OPTION);
            DaoObjeto dao = new DaoObjeto();
            boolean resp = (res==0?dao.Modificar(obj):false);
            if (resp == true) {
                JOptionPane.showMessageDialog(null, "Modifico");                
            } else {
                JOptionPane.showMessageDialog(null, "No pudo modificar");
            }
            limpiar();
            Listar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmAgregarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmAgregarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmAgregarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmAgregarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmAgregarObjeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboColor;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTable jtblLista;
    private javax.swing.JSpinner spnId_objeto;
    private javax.swing.JSpinner spnId_sala;
    private javax.swing.JTextField txtEncontradoRut;
    private javax.swing.JTextField txtRecibidoRut;
    private javax.swing.JTextField txtdesc_objeto;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        spnId_objeto.setValue(1);
        txtdesc_objeto.setText("");
        cboTipo.setSelectedItem("Teconologia");
        cboColor.setSelectedItem("Negro");
        Date fecha = new Date();
        jdcFecha.setDate(fecha);
        spnId_sala.setValue(1);
        txtEncontradoRut.setText("");
        txtRecibidoRut.setText("");
    }

    private void Listar() {
        DefaultTableModel modelo = new DefaultTableModel();
        jtblLista.setModel(modelo);
        modelo.addColumn("Id_objeto");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Tipo");
        modelo.addColumn("Color");
        modelo.addColumn("Fecha_encontrado");
        modelo.addColumn("Id_sala");
        ArrayList <Objeto> lista = new DaoObjeto().Listar();
        for (Objeto objeto : lista) {
            Object [] fila = new Object[8];
            fila[0]=objeto.getId_objeto();
            fila[1]=objeto.getDescripcion_objeto();
            fila[2]=objeto.getTipo();
            fila[3]=objeto.getColor();
            fila[4]=objeto.getFecha_encontrado();
            fila[5]=objeto.getSala().getId_sala();
            fila [6]=objeto.getEncontrado().getRut_encontrado();
            fila [7] = objeto.getRecibido().getNombre_recibido();
            modelo.addRow(fila);
        }
    }
}
