package vista;
import controlador.DaoEncontrado;
import javax.swing.DefaultComboBoxModel;
import enumeradores.EnumEscuela;
import enumeradores.EnumSemestre;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import modelo.Encontrado;


public class JFrmAgregarEncontrado extends javax.swing.JFrame {

    /**
     * Creates new form JFrmAgregarEncontrado
     */
    public JFrmAgregarEncontrado() {
        initComponents();
        setLocationRelativeTo(null);
        cboEscuela.setModel(new DefaultComboBoxModel(EnumEscuela.values()));
        cboSemestre.setModel(new DefaultComboBoxModel(EnumSemestre.values()));
        Listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jtblLista = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtxNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboEscuela = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        cboSemestre = new javax.swing.JComboBox<>();
        txtApellido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jtblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtblLista);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Encontrado por..."));

        jLabel1.setText("Rut encontrado por:");

        jLabel2.setText("Nombre encontrado por:");

        jButton1.setText("Grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido encontrado por:");

        jLabel4.setText("Escuela:");

        cboEscuela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Semestre: ");

        cboSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(txtRut))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtxNombre)
                                    .addComponent(txtApellido))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String rut_encontrado = txtRut.getText();
        String nombre_encontrado =txtxNombre.getText();
        String apellido_encontrado = txtApellido.getText();
        String escuela = cboEscuela.getSelectedItem().toString();
        EnumEscuela enum_escuela = null;
        if (escuela.equals("Administracion_negocios")) {
            enum_escuela = EnumEscuela.Administracion_negocios;}
        if (escuela.equals("Disenio")){
            enum_escuela = EnumEscuela.Disenio;}
        if (escuela.equals("Ingenieria")){
            enum_escuela = EnumEscuela.Ingenieria;}
        if (escuela.equals("Comunicacion")){
            enum_escuela = EnumEscuela.Comunicacion;}
        if (escuela.equals("Gastronomia")){
            enum_escuela = EnumEscuela.Gastronomia;}
        if (escuela.equals("Salud")){
            enum_escuela = EnumEscuela.Salud;}
        if (escuela.equals("Construccion")){
            enum_escuela = EnumEscuela.Construccion;}
        if (escuela.equals("Informatica_telecomunicaciones")){
            enum_escuela = EnumEscuela.Informatica_telecomunicaciones;}
        if (escuela.equals("Turismo_hoteleria")){
            enum_escuela = EnumEscuela.Turismo_hoteleria;}
        String semestre = cboSemestre.getSelectedItem().toString();
        EnumSemestre enum_semestre = null;
        if (semestre.equals("S1")) {
            enum_semestre = EnumSemestre.S1;}
        if (semestre.equals("S2")) {
            enum_semestre = EnumSemestre.S2;}
        if (semestre.equals("S3")) {
            enum_semestre = EnumSemestre.S3;}
        if (semestre.equals("S4")) {
            enum_semestre = EnumSemestre.S4;}
        if (semestre.equals("S5")) {
            enum_semestre = EnumSemestre.S5;}
        if (semestre.equals("S6")) {
            enum_semestre = EnumSemestre.S6;}
        if (semestre.equals("S7")) {
            enum_semestre = EnumSemestre.S7;}
        if (semestre.equals("S8")) {
            enum_semestre = EnumSemestre.S8;}

        try {
            Encontrado enc = new Encontrado(rut_encontrado, nombre_encontrado, apellido_encontrado, enum_escuela, enum_semestre);
            DaoEncontrado dao = new DaoEncontrado();
            boolean resp = dao.Grabar(enc);
            if (resp == true) {
                JOptionPane.showMessageDialog(null, "Grabo");
                limpiar();
                Listar();
            } else {
                JOptionPane.showMessageDialog(null, "No Grabo");
                limpiar();
                Listar();
            }
        } catch (Exception e) {
            System.out.println("Error Grabar encontrado:"+e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int pos_fila = jtblLista.getSelectedRow();
        String rut_encontrado = (jtblLista.getValueAt(pos_fila, 0).toString());
        try {
            DaoEncontrado dao = new DaoEncontrado();
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea eliminar encontrado? "+rut_encontrado,
                "Eliminar Encontrado", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {
                boolean resp = dao.Eliminar(rut_encontrado);
                if (resp) {
                    JOptionPane.showMessageDialog(null, "Eliminado");
                    limpiar();
                    Listar();
                } else {
                    JOptionPane.showMessageDialog(null, "No pudo eliminar");
                    limpiar();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error eliminar");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String rut_recibido = txtRut.getText();
        String nombre_recibido =txtxNombre.getText();
        String apellido_recibido = txtApellido.getText();
        String escuela = cboEscuela.getSelectedItem().toString();
        EnumEscuela enum_escuela = null;
        if (escuela.equals("Administracion_negocios")) {
            enum_escuela = EnumEscuela.Administracion_negocios;}
        if (escuela.equals("Disenio")){
            enum_escuela = EnumEscuela.Disenio;}
        if (escuela.equals("Ingenieria")){
            enum_escuela = EnumEscuela.Ingenieria;}
        if (escuela.equals("Comunicacion")){
            enum_escuela = EnumEscuela.Comunicacion;}
        if (escuela.equals("Gastronomia")){
            enum_escuela = EnumEscuela.Gastronomia;}
        if (escuela.equals("Salud")){
            enum_escuela = EnumEscuela.Salud;}
        if (escuela.equals("Construccion")){
            enum_escuela = EnumEscuela.Construccion;}
        if (escuela.equals("Informatica_telecomunicaciones")){
            enum_escuela = EnumEscuela.Informatica_telecomunicaciones;}
        if (escuela.equals("Turismo_hoteleria")){
            enum_escuela = EnumEscuela.Turismo_hoteleria;}
        String semestre = cboSemestre.getSelectedItem().toString();
        EnumSemestre enum_semestre = null;
        if (semestre.equals("S1")) {
            enum_semestre = EnumSemestre.S1;}
        if (semestre.equals("S2")) {
            enum_semestre = EnumSemestre.S2;}
        if (semestre.equals("S3")) {
            enum_semestre = EnumSemestre.S3;}
        if (semestre.equals("S4")) {
            enum_semestre = EnumSemestre.S4;}
        if (semestre.equals("S5")) {
            enum_semestre = EnumSemestre.S5;}
        if (semestre.equals("S6")) {
            enum_semestre = EnumSemestre.S6;}
        if (semestre.equals("S7")) {
            enum_semestre = EnumSemestre.S7;}
        if (semestre.equals("S8")) {
            enum_semestre = EnumSemestre.S8;}
        try {
            Encontrado rec = new Encontrado(rut_recibido, nombre_recibido, apellido_recibido, enum_escuela, enum_semestre);
            int res= JOptionPane.showConfirmDialog(null, "Modificar","Modificar registro",
                JOptionPane.YES_NO_OPTION);
            DaoEncontrado dao = new DaoEncontrado();
            boolean resp = (res==0?dao.Modificar(rec):false);
            if (resp == true) {
                JOptionPane.showMessageDialog(null, "Modifico");
            } else {
                JOptionPane.showMessageDialog(null, "No pudo modificar");
            }
            limpiar();
            Listar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmAgregarEncontrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmAgregarEncontrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmAgregarEncontrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmAgregarEncontrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmAgregarEncontrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboEscuela;
    private javax.swing.JComboBox<String> cboSemestre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtblLista;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtxNombre;
    // End of variables declaration//GEN-END:variables

    private void Listar() {
        DefaultTableModel modelo = new DefaultTableModel();
        jtblLista.setModel(modelo);
        modelo.addColumn("Rut");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Escuela");
        modelo.addColumn("Semestre");
        ArrayList <Encontrado> lista = new DaoEncontrado().Listar();
        for (Encontrado rec : lista) {
            Object [] fila = new Object[5];
            fila[0]=rec.getRut_encontrado();
            fila[1]=rec.getNombre_encontrado();
            fila[2]=rec.getApellido_encontrado();
            fila[3]=rec.getEscuela();
            fila[4]=rec.getSemestre();
            modelo.addRow(fila);
    }
    }

    private void limpiar() {
        txtRut.setText("");
        txtxNombre.setText("");
        txtApellido.setText("");
        cboEscuela.setSelectedItem("Administracion_negocios");
        cboSemestre.setSelectedItem("S1");
    }
}
